[package]
name = "d3dcompiler"
version = "0.1.0"
authors = ["Russell Johnston <rpjohnst@gmail.com>"]
edition = "2021"

[target.'cfg(windows)'.dependencies]
win32 = { path = "../win32" }
winapi = { version = "0.3", features = ["d3dcompiler"] }
