[package]
name = "gml-meta"
version = "0.1.0"
authors = ["Russell Johnston <rpjohnst@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = { version = "0.15", features = ["full", "extra-traits", "visit-mut"] }
quote = "0.6"
