[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[dependencies]
gml = { path = "../../gml" }
runner = { path = "../../runner" }
project = { path = "../../project", features = ["read"] }
quickdry = "0.1.2"
