[package]
name = "playground"
version = "0.1.0"
authors = ["Russell Johnston <rpjohnst@gmail.com>"]
edition = "2018"

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
dwarf-debug-info = true

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
gml = { path = "../gml" }
runner = { path = "../runner" }
project = { path = "../project" }
wasm-bindgen = "0.2"
