[package]
name = "playground"
version = "0.1.0"
authors = ["Russell Johnston <rpjohnst@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gml = { path = "../gml" }
engine = { path = "../engine" }
project = { path = "../project" }
wasm-host = { path = "../wasm-host" }
wasm-bindgen = "0.2"
js-sys = "0.3"
