on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --locked
    - name: Test
      run: cargo test --locked

  playground:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
    - name: wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        wasm-pack build --target web playground -- --locked
        npm ci --prefix playground
        npm run --prefix playground build
    - name: Deploy
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        source_dir: playground/public
        container_name: $web
        connection_string: ${{ secrets.ConnectionString }}
        sync: true
