name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --locked
    - name: Test
      run: cargo test --locked

  playground:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
    - name: wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        wasm-pack build --target web playground -- --locked
        npm ci --prefix playground
        npm run --prefix playground build
    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy
      run: |
        az storage blob sync --account-name dejavu --container \$web --source playground/public
        az cdn endpoint purge --resource-group dejavu --profile-name dejavu --name dejavu --content-paths "/*"
