name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --locked
    - name: Test
      run: cargo test --locked

  playground:
    runs-on: ubuntu-latest
    steps:
    - name: Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
        profile: minimal
    - name: Binaryen
      run: |
        curl -s -L https://github.com/WebAssembly/binaryen/releases/download/version_104/binaryen-version_104-x86_64-linux.tar.gz | tar -xzf - -C ~
        echo "$HOME/binaryen-version_104/bin" >> $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      working-directory: playground
      run: |
        cargo build --release --locked
        wasm-opt -Os -o src/playground.wasm ../target/wasm32-unknown-unknown/release/playground.wasm
        npm ci
        npm run build
    - name: Login
      if: github.event_name == 'push'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy
      if: github.event_name == 'push'
      run: |
        az storage blob sync --account-name dejavu --container \$web --source playground/public
        az cdn endpoint purge --resource-group dejavu --profile-name dejavu --name dejavu --content-paths "/*"
